server:
  port: 8083
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/coding_education
#      url: jdbc:mysql://localhost:3306/springboottry
      username: root
      password: root
  mail:
    username: 3282145600@qq.com
    password: rkjogdexonimdbbg
    host: smtp.qq.com
    default-encoding: UTF-8

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

